plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mfumowako.link2apk'
    compileSdk 34

    defaultConfig {
        applicationId "com.mfumowako.link2apk"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // Hii inahitajika kwa sababu unatumia SwipeRefreshLayout kwenye activity_main.xml
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    
    // CODE YA ADMOB (Google Mobile Ads SDK)
    implementation 'com.google.android.gms:play-services-ads:23.0.0'

    // CODE YA ONESIGNAL (Ili kuzuia ile error ya ApplicationClass)
    implementation 'com.onesignal:OneSignal:5.1.2'
}
