name: Tengeneza Link2APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Jina la App Yako'
        required: true
        default: 'Aplikasi Yangu'
      target_url:
        description: 'Link ya Tovuti Yako'
        required: true
        default: 'https://www.google.com'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kushusha kodi kutoka Repository
      uses: actions/checkout@v4

    - name: Kuweka Java mazingira ya kazi
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Kuingiza Link na Jina la Mteja kwenye Kodi ya Android
      run: |
        mkdir -p app/src/main/java/com/mfumowako/link2apk
        sed -i 's|private static final String TARGET_URL = "https://www.google.com";|private static final String TARGET_URL = "${{ github.event.inputs.target_url }}";|g' app/src/main/java/com/mfumowako/link2apk/MainActivity.java
        sed -i 's/android:label="Link2APK App"/android:label="${{ github.event.inputs.app_name }}"/g' app/src/main/AndroidManifest.xml

    - name: Kutoa ruhusa ya kiusalama kwa gradlew
      run: chmod +x gradlew

    - name: Kuanza kutengeneza APK na Kuweka Saini
      run: ./gradlew assembleDebug

    - name: Kuhifadhi APK iliyokamilika
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.app_name }}-APK
        path: app/build/outputs/apk/debug/app-debug.apk
